name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
          standalone: true
          dest: ~/setup-pnpm
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: pnpm
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: pnpm install
      - name: Build library
        run: pnpm run build
      - name: Publish library
        run: pnpm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
